name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "43 5 * * MON-FRI" # Every weekday
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v0.7 # WORKFLOW_VERSION
    with:
      channel_id: hmpps-sre-alerts-nonprod
    secrets: inherit
